version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: dpg-cvpt6mbe5dus739p8q10-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: phptest
      DB_USER: phptest_user
      DB_PASS: G1uWFL5bapSbv4o8pDElFkXhZB97e11p
